<?php
$attributes=[
	'className'=>['type'=>'string'],
	'content_path'=>['type'=>'string'],
	'post_data_path'=>['type'=>'string'],
	'inputs'=>['type'=>'string'],
	'data_id'=>['type'=>'string'],
	'values'=>['type'=>'string']
];