var Fragment = wp.element.Fragment;
var _wp$blocks = wp.blocks,
    registerBlockType = _wp$blocks.registerBlockType,
    createBlock = _wp$blocks.createBlock;
var _wp$blockEditor = wp.blockEditor,
    InnerBlocks = _wp$blockEditor.InnerBlocks,
    BlockControls = _wp$blockEditor.BlockControls,
    AlignmentToolbar = _wp$blockEditor.AlignmentToolbar,
    BlockAlignmentToolbar = _wp$blockEditor.BlockAlignmentToolbar,
    BlockVerticalAlignmentToolbar = _wp$blockEditor.BlockVerticalAlignmentToolbar,
    PanelColorSettings = _wp$blockEditor.PanelColorSettings,
    PanelColorGradientSettings = _wp$blockEditor.PanelColorGradientSettings,
    InspectorControls = _wp$blockEditor.InspectorControls,
    RichText = _wp$blockEditor.RichText,
    RichTextToolbarButton = _wp$blockEditor.RichTextToolbarButton,
    RichTextShortcut = _wp$blockEditor.RichTextShortcut;
var _wp$components = wp.components,
    PanelBody = _wp$components.PanelBody,
    BaseControl = _wp$components.BaseControl,
    TreeSelect = _wp$components.TreeSelect,
    TextareaControl = _wp$components.TextareaControl,
    TextControl = _wp$components.TextControl,
    ServerSideRender = _wp$components.ServerSideRender,
    ToggleControl = _wp$components.ToggleControl,
    SelectControl = _wp$components.SelectControl,
    CheckboxControl = _wp$components.CheckboxControl,
    RadioControl = _wp$components.RadioControl,
    RangeControl = _wp$components.RangeControl,
    Button = _wp$components.Button,
    Toolbar = _wp$components.Toolbar,
    FormFileUpload = _wp$components.FormFileUpload,
    Icon = _wp$components.Icon;
var _wp$richText = wp.richText,
    registerFormatType = _wp$richText.registerFormatType,
    toggleFormat = _wp$richText.toggleFormat;
var __ = wp.i18n.__;
var el = wp.element.createElement;
var registerPlugin = wp.plugins.registerPlugin;
var _wp$editPost = wp.editPost,
    PluginSidebarMoreMenuItem = _wp$editPost.PluginSidebarMoreMenuItem,
    PluginSidebar = _wp$editPost.PluginSidebar;
