<?php
$block_class="wp-block-catpow-artframe";
$attributes=[
	"color"=>["type"=>"string","default"=>"0"],
	"classes"=>["type"=>"string","selector"=>".{$block_class}","attribute"=>"class","default"=>$block_class],
	"contentsClasses"=>["type"=>"string","selector"=>".{$block_class}__contents","attribute"=>"class","default"=>"{$block_class}__contents"],
	"contentsBodyClasses"=>["type"=>"string","selector"=>".{$block_class}__contents-body","attribute"=>"class","default"=>"{$block_class}__contents-body"],
	"vars"=>["type"=>"object","default"=>[]],
	"element"=>["type"=>"string"],
	"params"=>["type"=>"object","default"=>[]],
];