<?php
$attributes=[
	'schedule'=>['type'=>'string','default'=>''],
	'is_user_logged_in'=>['type'=>'string','default'=>'0'],
	'current_user_can'=>['type'=>'string','default'=>''],
	'user_value'=>['type'=>'string','default'=>''],
	'input_value'=>['type'=>'string','default'=>''],
	'content_value'=>['type'=>'string','default'=>'']
];