<?php
$useScripts=['catpow','catpow.schema'];
$useComponents=[
	'InputDateTime','InputDuration','InputTextItems',
	'Calendar','CheckBox','CheckBoxes',
	'RadioButtons',
	'SelectBox','SearchSelect','StepSelect',
	'SelectMedia','SelectPreparedImage','SelectPreparedImageSet',
	'SelectNumber',
	'SelectMenuItem',
	'Toggle',
	'ArrayInput','TableInput',
	'Popover','Popup',
];