<?php
$useScripts=['catpow','catpow.schema'];
$useComponents=[
	'Calendar','CheckBox','CheckBoxes',
	'InputDateTime','InputDuration','InputTextItems',
	'RadioButtons','SearchSelect',
	'SelectMedia','SelectPreparedImage','SelectPreparedImageSet',
	'SelectNumber',
	'SelectMenuItem',
	'Toggle','ArrayInput'
];